// packages/client/src/GameCreationForm.tsx
import { getVariantList } from "@ogfcommunity/variants-shared";
import * as requests from "./requests";
import { useState } from "react";
import { useNavigate } from "react-router-dom";

export function GameCreationForm() {
  const [config_string, setConfigString] = useState(
    '{ "width": 19, "height": 19, "komi": 5.5 }'
  );
  const [variant, setVariant] = useState("baduk");
  const navigate = useNavigate();
  const createGame = async () => {
    requests
      .post("/games", { variant, config: JSON.parse(config_string) })
      .then((game) => navigate(`/game/${game.id}`));
  };

  return (
    <div className="game-creation-form">
      <h3>Create a game</h3>
      <div>
        <label>Variant:</label>
        <select
          onChange={(ev) => {
            setVariant(ev.target.value);
          }}
        >
          {getVariantList().map((v) => (
            <option key={v} value={v}>
              {v}
            </option>
          ))}
        </select>
      </div>
      <div>
        <label>Config: </label>
        <textarea
          onChange={(ev) => {
            setConfigString(ev.target.value);
          }}
          value={config_string}
        />
      </div>
      <button onClick={createGame}>Create Game</button>
    </div>
  );
}

// packages/vue-client/src/components/GameCreationForm.vue
<script setup lang="ts">
import { ref, type Ref, watch } from "vue";
import {
  getVariantList,
  getDefaultConfig,
} from "@ogfcommunity/variants-shared";
import router from "@/router";
import * as requests from "@/requests";

const variants: string[] = getVariantList();
const variant: Ref<string> = ref(variants.length ? variants[0] : "");
const config: Ref<string> = ref("");
watch(
  variant,
  () => {
    config.value = JSON.stringify(getDefaultConfig(variant.value), null, 2);
  },
  { immediate: true }
);

const createGame = async () => {
  const game = await requests.post("/games", {
    variant: variant.value,
    config: JSON.parse(config.value),
  });
  console.log(game);
  router.push({ name: "game", params: { gameId: game.id } });
};
</script>

<template>
  <div className="game-creation-form">
    <h3>Create a game</h3>
    <div>
      <label>Variant:</label>
      <select v-model="variant">
        <option v-for="variant in variants" :key="variant">
          {{ variant }}
        </option>
      </select>
    </div>
    <div>
      <label>Config: </label>
      <textarea v-model="config"></textarea>
    </div>
    <button v-on:click="createGame()">Create Game</button>
  </div>
</template>

<style>
textarea {
  width: 300px;
  height: 150px;
  display: block;
}
</style>
